# Generated by Django 4.0.4 on 2022-04-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobrecruiter',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('mobile', models.IntegerField()),
                ('pwsd', models.CharField(max_length=50)),
                ('repwsd', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('job_skills', models.CharField(max_length=150)),
                ('job_experiance', models.IntegerField()),
                ('job_company_name', models.CharField(max_length=50)),
                ('job_company_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='jobseeker',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('dob', models.DateField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('pwsd', models.CharField(max_length=50)),
                ('repwsd', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('passed_out_year', models.DateField(max_length=20)),
                ('percentile', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('applied_job', models.CharField(max_length=100)),
                ('applied_company', models.CharField(max_length=100)),
            ],
        ),
    ]
