# Generated by Django 4.0.4 on 2022-04-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobrecruiter',
            new_name='jobrecruiter_model',
        ),
        migrations.RenameModel(
            old_name='jobs',
            new_name='jobs_model',
        ),
        migrations.RenameModel(
            old_name='jobseeker',
            new_name='jobseeker_model',
        ),
    ]
