# Generated by Django 4.0.4 on 2022-04-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_jobrecruiter_jobrecruiter_model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jobrecruiter_model',
        ),
        migrations.DeleteModel(
            name='jobs_model',
        ),
    ]
