# Generated by Django 4.0.4 on 2022-04-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_jobrecruiter_model_delete_jobs_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobrecruiter_model',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('mobile', models.IntegerField()),
                ('pwsd', models.CharField(max_length=50)),
                ('repwsd', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='jobs_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('job_skills', models.CharField(max_length=150)),
                ('job_experiance', models.IntegerField()),
                ('job_company_name', models.CharField(max_length=50)),
                ('job_company_desc', models.CharField(max_length=50)),
            ],
        ),
    ]
