# Generated by Django 3.2.5 on 2022-04-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_jobrecruiter_model_jobs_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrecruiter_model',
            name='company_desc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobrecruiter_model',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
