# Generated by Django 4.0.4 on 2022-04-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20220430_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs_model',
            name='job_location',
        ),
    ]
