# Generated by Django 4.0.4 on 2022-04-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_jobs_model_job_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs_model',
            name='job_company_desc',
        ),
        migrations.RemoveField(
            model_name='jobs_model',
            name='job_experiance',
        ),
    ]
