# Generated by Django 4.0.4 on 2022-04-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_jobs_model_job_company_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs_model',
            name='job_experiance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
