# Generated by Django 4.0.4 on 2022-04-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_jobs_model_job_experiance'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs_model',
            name='job_company_email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
