# Generated by Django 4.0.4 on 2022-05-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_job_apply_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_apply_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='job_apply_model',
            name='job_title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
