# Generated by Django 4.0.4 on 2022-05-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_job_apply_model_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs_model',
            name='no_of_openings',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
