# Generated by Django 4.0.4 on 2022-05-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_jobs_model_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job_apply_model',
            unique_together={('job_title', 'job_seeker_email')},
        ),
    ]
