# Generated by Django 4.0.4 on 2022-05-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_job_apply_model_id_alter_job_apply_model_job_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job_apply_model',
            unique_together=set(),
        ),
    ]
